/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendrierEditorialRouteImport } from './routes/calendrier-editorial'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ConsultationsRouteImport } from './routes/consultations'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as OpportunitesRouteImport } from './routes/opportunites'
import { Route as ReseauxSociauxRouteImport } from './routes/reseaux-sociaux'
import { Route as OpportunitesIdRouteImport } from './routes/opportunites.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendrierEditorialRoute = CalendrierEditorialRouteImport.update({
  id: '/calendrier-editorial',
  path: '/calendrier-editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationsRoute = ConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitesRoute = OpportunitesRouteImport.update({
  id: '/opportunites',
  path: '/opportunites',
  getParentRoute: () => rootRouteImport,
} as any)
const ReseauxSociauxRoute = ReseauxSociauxRouteImport.update({
  id: '/reseaux-sociaux',
  path: '/reseaux-sociaux',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitesIdRoute = OpportunitesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpportunitesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendrier-editorial': typeof CalendrierEditorialRoute
  '/clients': typeof ClientsRoute
  '/consultations': typeof ConsultationsRoute
  '/devis': typeof DevisRoute
  '/opportunites': typeof OpportunitesRouteWithChildren
  '/reseaux-sociaux': typeof ReseauxSociauxRoute
  '/opportunites/$id': typeof OpportunitesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendrier-editorial': typeof CalendrierEditorialRoute
  '/clients': typeof ClientsRoute
  '/consultations': typeof ConsultationsRoute
  '/devis': typeof DevisRoute
  '/opportunites': typeof OpportunitesRouteWithChildren
  '/reseaux-sociaux': typeof ReseauxSociauxRoute
  '/opportunites/$id': typeof OpportunitesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendrier-editorial': typeof CalendrierEditorialRoute
  '/clients': typeof ClientsRoute
  '/consultations': typeof ConsultationsRoute
  '/devis': typeof DevisRoute
  '/opportunites': typeof OpportunitesRouteWithChildren
  '/reseaux-sociaux': typeof ReseauxSociauxRoute
  '/opportunites/$id': typeof OpportunitesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendrier-editorial'
    | '/clients'
    | '/consultations'
    | '/devis'
    | '/opportunites'
    | '/reseaux-sociaux'
    | '/opportunites/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendrier-editorial'
    | '/clients'
    | '/consultations'
    | '/devis'
    | '/opportunites'
    | '/reseaux-sociaux'
    | '/opportunites/$id'
  id:
    | '__root__'
    | '/'
    | '/calendrier-editorial'
    | '/clients'
    | '/consultations'
    | '/devis'
    | '/opportunites'
    | '/reseaux-sociaux'
    | '/opportunites/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendrierEditorialRoute: typeof CalendrierEditorialRoute
  ClientsRoute: typeof ClientsRoute
  ConsultationsRoute: typeof ConsultationsRoute
  DevisRoute: typeof DevisRoute
  OpportunitesRoute: typeof OpportunitesRouteWithChildren
  ReseauxSociauxRoute: typeof ReseauxSociauxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendrier-editorial': {
      id: '/calendrier-editorial'
      path: '/calendrier-editorial'
      fullPath: '/calendrier-editorial'
      preLoaderRoute: typeof CalendrierEditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations': {
      id: '/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof ConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunites': {
      id: '/opportunites'
      path: '/opportunites'
      fullPath: '/opportunites'
      preLoaderRoute: typeof OpportunitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseaux-sociaux': {
      id: '/reseaux-sociaux'
      path: '/reseaux-sociaux'
      fullPath: '/reseaux-sociaux'
      preLoaderRoute: typeof ReseauxSociauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunites/$id': {
      id: '/opportunites/$id'
      path: '/$id'
      fullPath: '/opportunites/$id'
      preLoaderRoute: typeof OpportunitesIdRouteImport
      parentRoute: typeof OpportunitesRoute
    }
  }
}

interface OpportunitesRouteChildren {
  OpportunitesIdRoute: typeof OpportunitesIdRoute
}

const OpportunitesRouteChildren: OpportunitesRouteChildren = {
  OpportunitesIdRoute: OpportunitesIdRoute,
}

const OpportunitesRouteWithChildren = OpportunitesRoute._addFileChildren(
  OpportunitesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendrierEditorialRoute: CalendrierEditorialRoute,
  ClientsRoute: ClientsRoute,
  ConsultationsRoute: ConsultationsRoute,
  DevisRoute: DevisRoute,
  OpportunitesRoute: OpportunitesRouteWithChildren,
  ReseauxSociauxRoute: ReseauxSociauxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
