/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendrierAoRouteImport } from './routes/calendrier-ao'
import { Route as CalendrierEditorialRouteImport } from './routes/calendrier-editorial'
import { Route as ConfigurationIaRouteImport } from './routes/configuration-ia'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DossiersRouteImport } from './routes/dossiers'
import { Route as EquipesRouteImport } from './routes/equipes'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OpportunitesDetecteesRouteImport } from './routes/opportunites-detectees'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as ReseauxSociauxRouteImport } from './routes/reseaux-sociaux'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as UtilisateursRouteImport } from './routes/utilisateurs'
import { Route as AffairesIndexRouteImport } from './routes/affaires.index'
import { Route as AffairesIdRouteImport } from './routes/affaires.$id'
import { Route as AppelsOffresIndexRouteImport } from './routes/appels-offres.index'
import { Route as AppelsOffresIdRouteImport } from './routes/appels-offres.$id'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as OpportunitesIndexRouteImport } from './routes/opportunites.index'
import { Route as OpportunitesIdRouteImport } from './routes/opportunites.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendrierAoRoute = CalendrierAoRouteImport.update({
  id: '/calendrier-ao',
  path: '/calendrier-ao',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendrierEditorialRoute = CalendrierEditorialRouteImport.update({
  id: '/calendrier-editorial',
  path: '/calendrier-editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationIaRoute = ConfigurationIaRouteImport.update({
  id: '/configuration-ia',
  path: '/configuration-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersRoute = DossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipesRoute = EquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitesDetecteesRoute = OpportunitesDetecteesRouteImport.update({
  id: '/opportunites-detectees',
  path: '/opportunites-detectees',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const ReseauxSociauxRoute = ReseauxSociauxRouteImport.update({
  id: '/reseaux-sociaux',
  path: '/reseaux-sociaux',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilisateursRoute = UtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const AffairesIndexRoute = AffairesIndexRouteImport.update({
  id: '/affaires/',
  path: '/affaires/',
  getParentRoute: () => rootRouteImport,
} as any)
const AffairesIdRoute = AffairesIdRouteImport.update({
  id: '/affaires/$id',
  path: '/affaires/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppelsOffresIndexRoute = AppelsOffresIndexRouteImport.update({
  id: '/appels-offres/',
  path: '/appels-offres/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppelsOffresIdRoute = AppelsOffresIdRouteImport.update({
  id: '/appels-offres/$id',
  path: '/appels-offres/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientsRoute,
} as any)
const OpportunitesIndexRoute = OpportunitesIndexRouteImport.update({
  id: '/opportunites/',
  path: '/opportunites/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitesIdRoute = OpportunitesIdRouteImport.update({
  id: '/opportunites/$id',
  path: '/opportunites/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendrier-ao': typeof CalendrierAoRoute
  '/calendrier-editorial': typeof CalendrierEditorialRoute
  '/configuration-ia': typeof ConfigurationIaRoute
  '/devis': typeof DevisRoute
  '/documents': typeof DocumentsRoute
  '/dossiers': typeof DossiersRoute
  '/equipes': typeof EquipesRoute
  '/notifications': typeof NotificationsRoute
  '/opportunites-detectees': typeof OpportunitesDetecteesRoute
  '/references': typeof ReferencesRoute
  '/reseaux-sociaux': typeof ReseauxSociauxRoute
  '/roles': typeof RolesRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/affaires/$id': typeof AffairesIdRoute
  '/appels-offres/$id': typeof AppelsOffresIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/opportunites/$id': typeof OpportunitesIdRoute
  '/affaires/': typeof AffairesIndexRoute
  '/appels-offres/': typeof AppelsOffresIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/opportunites/': typeof OpportunitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendrier-ao': typeof CalendrierAoRoute
  '/calendrier-editorial': typeof CalendrierEditorialRoute
  '/configuration-ia': typeof ConfigurationIaRoute
  '/devis': typeof DevisRoute
  '/documents': typeof DocumentsRoute
  '/dossiers': typeof DossiersRoute
  '/equipes': typeof EquipesRoute
  '/notifications': typeof NotificationsRoute
  '/opportunites-detectees': typeof OpportunitesDetecteesRoute
  '/references': typeof ReferencesRoute
  '/reseaux-sociaux': typeof ReseauxSociauxRoute
  '/roles': typeof RolesRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/affaires/$id': typeof AffairesIdRoute
  '/appels-offres/$id': typeof AppelsOffresIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/opportunites/$id': typeof OpportunitesIdRoute
  '/affaires': typeof AffairesIndexRoute
  '/appels-offres': typeof AppelsOffresIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/opportunites': typeof OpportunitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendrier-ao': typeof CalendrierAoRoute
  '/calendrier-editorial': typeof CalendrierEditorialRoute
  '/configuration-ia': typeof ConfigurationIaRoute
  '/devis': typeof DevisRoute
  '/documents': typeof DocumentsRoute
  '/dossiers': typeof DossiersRoute
  '/equipes': typeof EquipesRoute
  '/notifications': typeof NotificationsRoute
  '/opportunites-detectees': typeof OpportunitesDetecteesRoute
  '/references': typeof ReferencesRoute
  '/reseaux-sociaux': typeof ReseauxSociauxRoute
  '/roles': typeof RolesRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/affaires/$id': typeof AffairesIdRoute
  '/appels-offres/$id': typeof AppelsOffresIdRoute
  '/clients/$id': typeof ClientsIdRoute
  '/opportunites/$id': typeof OpportunitesIdRoute
  '/affaires/': typeof AffairesIndexRoute
  '/appels-offres/': typeof AppelsOffresIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/opportunites/': typeof OpportunitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendrier-ao'
    | '/calendrier-editorial'
    | '/configuration-ia'
    | '/devis'
    | '/documents'
    | '/dossiers'
    | '/equipes'
    | '/notifications'
    | '/opportunites-detectees'
    | '/references'
    | '/reseaux-sociaux'
    | '/roles'
    | '/utilisateurs'
    | '/affaires/$id'
    | '/appels-offres/$id'
    | '/clients/$id'
    | '/opportunites/$id'
    | '/affaires/'
    | '/appels-offres/'
    | '/clients/'
    | '/opportunites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendrier-ao'
    | '/calendrier-editorial'
    | '/configuration-ia'
    | '/devis'
    | '/documents'
    | '/dossiers'
    | '/equipes'
    | '/notifications'
    | '/opportunites-detectees'
    | '/references'
    | '/reseaux-sociaux'
    | '/roles'
    | '/utilisateurs'
    | '/affaires/$id'
    | '/appels-offres/$id'
    | '/clients/$id'
    | '/opportunites/$id'
    | '/affaires'
    | '/appels-offres'
    | '/clients'
    | '/opportunites'
  id:
    | '__root__'
    | '/'
    | '/calendrier-ao'
    | '/calendrier-editorial'
    | '/configuration-ia'
    | '/devis'
    | '/documents'
    | '/dossiers'
    | '/equipes'
    | '/notifications'
    | '/opportunites-detectees'
    | '/references'
    | '/reseaux-sociaux'
    | '/roles'
    | '/utilisateurs'
    | '/affaires/$id'
    | '/appels-offres/$id'
    | '/clients/$id'
    | '/opportunites/$id'
    | '/affaires/'
    | '/appels-offres/'
    | '/clients/'
    | '/opportunites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendrierAoRoute: typeof CalendrierAoRoute
  CalendrierEditorialRoute: typeof CalendrierEditorialRoute
  ConfigurationIaRoute: typeof ConfigurationIaRoute
  DevisRoute: typeof DevisRoute
  DocumentsRoute: typeof DocumentsRoute
  DossiersRoute: typeof DossiersRoute
  EquipesRoute: typeof EquipesRoute
  NotificationsRoute: typeof NotificationsRoute
  OpportunitesDetecteesRoute: typeof OpportunitesDetecteesRoute
  ReferencesRoute: typeof ReferencesRoute
  ReseauxSociauxRoute: typeof ReseauxSociauxRoute
  RolesRoute: typeof RolesRoute
  UtilisateursRoute: typeof UtilisateursRoute
  AffairesIdRoute: typeof AffairesIdRoute
  AppelsOffresIdRoute: typeof AppelsOffresIdRoute
  OpportunitesIdRoute: typeof OpportunitesIdRoute
  AffairesIndexRoute: typeof AffairesIndexRoute
  AppelsOffresIndexRoute: typeof AppelsOffresIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  OpportunitesIndexRoute: typeof OpportunitesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendrier-ao': {
      id: '/calendrier-ao'
      path: '/calendrier-ao'
      fullPath: '/calendrier-ao'
      preLoaderRoute: typeof CalendrierAoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendrier-editorial': {
      id: '/calendrier-editorial'
      path: '/calendrier-editorial'
      fullPath: '/calendrier-editorial'
      preLoaderRoute: typeof CalendrierEditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration-ia': {
      id: '/configuration-ia'
      path: '/configuration-ia'
      fullPath: '/configuration-ia'
      preLoaderRoute: typeof ConfigurationIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers': {
      id: '/dossiers'
      path: '/dossiers'
      fullPath: '/dossiers'
      preLoaderRoute: typeof DossiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipes': {
      id: '/equipes'
      path: '/equipes'
      fullPath: '/equipes'
      preLoaderRoute: typeof EquipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunites-detectees': {
      id: '/opportunites-detectees'
      path: '/opportunites-detectees'
      fullPath: '/opportunites-detectees'
      preLoaderRoute: typeof OpportunitesDetecteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseaux-sociaux': {
      id: '/reseaux-sociaux'
      path: '/reseaux-sociaux'
      fullPath: '/reseaux-sociaux'
      preLoaderRoute: typeof ReseauxSociauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilisateurs': {
      id: '/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof UtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affaires/': {
      id: '/affaires/'
      path: '/affaires'
      fullPath: '/affaires/'
      preLoaderRoute: typeof AffairesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affaires/$id': {
      id: '/affaires/$id'
      path: '/affaires/$id'
      fullPath: '/affaires/$id'
      preLoaderRoute: typeof AffairesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appels-offres/': {
      id: '/appels-offres/'
      path: '/appels-offres'
      fullPath: '/appels-offres/'
      preLoaderRoute: typeof AppelsOffresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appels-offres/$id': {
      id: '/appels-offres/$id'
      path: '/appels-offres/$id'
      fullPath: '/appels-offres/$id'
      preLoaderRoute: typeof AppelsOffresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/opportunites/': {
      id: '/opportunites/'
      path: '/opportunites'
      fullPath: '/opportunites/'
      preLoaderRoute: typeof OpportunitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunites/$id': {
      id: '/opportunites/$id'
      path: '/opportunites/$id'
      fullPath: '/opportunites/$id'
      preLoaderRoute: typeof OpportunitesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendrierAoRoute: CalendrierAoRoute,
  CalendrierEditorialRoute: CalendrierEditorialRoute,
  ConfigurationIaRoute: ConfigurationIaRoute,
  DevisRoute: DevisRoute,
  DocumentsRoute: DocumentsRoute,
  DossiersRoute: DossiersRoute,
  EquipesRoute: EquipesRoute,
  NotificationsRoute: NotificationsRoute,
  OpportunitesDetecteesRoute: OpportunitesDetecteesRoute,
  ReferencesRoute: ReferencesRoute,
  ReseauxSociauxRoute: ReseauxSociauxRoute,
  RolesRoute: RolesRoute,
  UtilisateursRoute: UtilisateursRoute,
  AffairesIdRoute: AffairesIdRoute,
  AppelsOffresIdRoute: AppelsOffresIdRoute,
  OpportunitesIdRoute: OpportunitesIdRoute,
  AffairesIndexRoute: AffairesIndexRoute,
  AppelsOffresIndexRoute: AppelsOffresIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  OpportunitesIndexRoute: OpportunitesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
