/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AffairesRouteImport } from './routes/affaires'
import { Route as AppelsOffresRouteImport } from './routes/appels-offres'
import { Route as CalendrierAoRouteImport } from './routes/calendrier-ao'
import { Route as CalendrierEditorialRouteImport } from './routes/calendrier-editorial'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CommandesRouteImport } from './routes/commandes'
import { Route as CommandesInternesRouteImport } from './routes/commandes-internes'
import { Route as ConsultationsRouteImport } from './routes/consultations'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as DossiersRouteImport } from './routes/dossiers'
import { Route as OpportunitesRouteImport } from './routes/opportunites'
import { Route as OpportunitesDetecteesRouteImport } from './routes/opportunites-detectees'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as ReseauxSociauxRouteImport } from './routes/reseaux-sociaux'
import { Route as AppelsOffresIdRouteImport } from './routes/appels-offres.$id'
import { Route as OpportunitesIdRouteImport } from './routes/opportunites.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AffairesRoute = AffairesRouteImport.update({
  id: '/affaires',
  path: '/affaires',
  getParentRoute: () => rootRouteImport,
} as any)
const AppelsOffresRoute = AppelsOffresRouteImport.update({
  id: '/appels-offres',
  path: '/appels-offres',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendrierAoRoute = CalendrierAoRouteImport.update({
  id: '/calendrier-ao',
  path: '/calendrier-ao',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendrierEditorialRoute = CalendrierEditorialRouteImport.update({
  id: '/calendrier-editorial',
  path: '/calendrier-editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesRoute = CommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesInternesRoute = CommandesInternesRouteImport.update({
  id: '/commandes-internes',
  path: '/commandes-internes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationsRoute = ConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersRoute = DossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitesRoute = OpportunitesRouteImport.update({
  id: '/opportunites',
  path: '/opportunites',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitesDetecteesRoute = OpportunitesDetecteesRouteImport.update({
  id: '/opportunites-detectees',
  path: '/opportunites-detectees',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const ReseauxSociauxRoute = ReseauxSociauxRouteImport.update({
  id: '/reseaux-sociaux',
  path: '/reseaux-sociaux',
  getParentRoute: () => rootRouteImport,
} as any)
const AppelsOffresIdRoute = AppelsOffresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppelsOffresRoute,
} as any)
const OpportunitesIdRoute = OpportunitesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpportunitesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affaires': typeof AffairesRoute
  '/appels-offres': typeof AppelsOffresRouteWithChildren
  '/calendrier-ao': typeof CalendrierAoRoute
  '/calendrier-editorial': typeof CalendrierEditorialRoute
  '/clients': typeof ClientsRoute
  '/commandes': typeof CommandesRoute
  '/commandes-internes': typeof CommandesInternesRoute
  '/consultations': typeof ConsultationsRoute
  '/devis': typeof DevisRoute
  '/dossiers': typeof DossiersRoute
  '/opportunites': typeof OpportunitesRouteWithChildren
  '/opportunites-detectees': typeof OpportunitesDetecteesRoute
  '/references': typeof ReferencesRoute
  '/reseaux-sociaux': typeof ReseauxSociauxRoute
  '/appels-offres/$id': typeof AppelsOffresIdRoute
  '/opportunites/$id': typeof OpportunitesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affaires': typeof AffairesRoute
  '/appels-offres': typeof AppelsOffresRouteWithChildren
  '/calendrier-ao': typeof CalendrierAoRoute
  '/calendrier-editorial': typeof CalendrierEditorialRoute
  '/clients': typeof ClientsRoute
  '/commandes': typeof CommandesRoute
  '/commandes-internes': typeof CommandesInternesRoute
  '/consultations': typeof ConsultationsRoute
  '/devis': typeof DevisRoute
  '/dossiers': typeof DossiersRoute
  '/opportunites': typeof OpportunitesRouteWithChildren
  '/opportunites-detectees': typeof OpportunitesDetecteesRoute
  '/references': typeof ReferencesRoute
  '/reseaux-sociaux': typeof ReseauxSociauxRoute
  '/appels-offres/$id': typeof AppelsOffresIdRoute
  '/opportunites/$id': typeof OpportunitesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affaires': typeof AffairesRoute
  '/appels-offres': typeof AppelsOffresRouteWithChildren
  '/calendrier-ao': typeof CalendrierAoRoute
  '/calendrier-editorial': typeof CalendrierEditorialRoute
  '/clients': typeof ClientsRoute
  '/commandes': typeof CommandesRoute
  '/commandes-internes': typeof CommandesInternesRoute
  '/consultations': typeof ConsultationsRoute
  '/devis': typeof DevisRoute
  '/dossiers': typeof DossiersRoute
  '/opportunites': typeof OpportunitesRouteWithChildren
  '/opportunites-detectees': typeof OpportunitesDetecteesRoute
  '/references': typeof ReferencesRoute
  '/reseaux-sociaux': typeof ReseauxSociauxRoute
  '/appels-offres/$id': typeof AppelsOffresIdRoute
  '/opportunites/$id': typeof OpportunitesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affaires'
    | '/appels-offres'
    | '/calendrier-ao'
    | '/calendrier-editorial'
    | '/clients'
    | '/commandes'
    | '/commandes-internes'
    | '/consultations'
    | '/devis'
    | '/dossiers'
    | '/opportunites'
    | '/opportunites-detectees'
    | '/references'
    | '/reseaux-sociaux'
    | '/appels-offres/$id'
    | '/opportunites/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affaires'
    | '/appels-offres'
    | '/calendrier-ao'
    | '/calendrier-editorial'
    | '/clients'
    | '/commandes'
    | '/commandes-internes'
    | '/consultations'
    | '/devis'
    | '/dossiers'
    | '/opportunites'
    | '/opportunites-detectees'
    | '/references'
    | '/reseaux-sociaux'
    | '/appels-offres/$id'
    | '/opportunites/$id'
  id:
    | '__root__'
    | '/'
    | '/affaires'
    | '/appels-offres'
    | '/calendrier-ao'
    | '/calendrier-editorial'
    | '/clients'
    | '/commandes'
    | '/commandes-internes'
    | '/consultations'
    | '/devis'
    | '/dossiers'
    | '/opportunites'
    | '/opportunites-detectees'
    | '/references'
    | '/reseaux-sociaux'
    | '/appels-offres/$id'
    | '/opportunites/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffairesRoute: typeof AffairesRoute
  AppelsOffresRoute: typeof AppelsOffresRouteWithChildren
  CalendrierAoRoute: typeof CalendrierAoRoute
  CalendrierEditorialRoute: typeof CalendrierEditorialRoute
  ClientsRoute: typeof ClientsRoute
  CommandesRoute: typeof CommandesRoute
  CommandesInternesRoute: typeof CommandesInternesRoute
  ConsultationsRoute: typeof ConsultationsRoute
  DevisRoute: typeof DevisRoute
  DossiersRoute: typeof DossiersRoute
  OpportunitesRoute: typeof OpportunitesRouteWithChildren
  OpportunitesDetecteesRoute: typeof OpportunitesDetecteesRoute
  ReferencesRoute: typeof ReferencesRoute
  ReseauxSociauxRoute: typeof ReseauxSociauxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affaires': {
      id: '/affaires'
      path: '/affaires'
      fullPath: '/affaires'
      preLoaderRoute: typeof AffairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appels-offres': {
      id: '/appels-offres'
      path: '/appels-offres'
      fullPath: '/appels-offres'
      preLoaderRoute: typeof AppelsOffresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendrier-ao': {
      id: '/calendrier-ao'
      path: '/calendrier-ao'
      fullPath: '/calendrier-ao'
      preLoaderRoute: typeof CalendrierAoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendrier-editorial': {
      id: '/calendrier-editorial'
      path: '/calendrier-editorial'
      fullPath: '/calendrier-editorial'
      preLoaderRoute: typeof CalendrierEditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes': {
      id: '/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof CommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes-internes': {
      id: '/commandes-internes'
      path: '/commandes-internes'
      fullPath: '/commandes-internes'
      preLoaderRoute: typeof CommandesInternesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations': {
      id: '/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof ConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers': {
      id: '/dossiers'
      path: '/dossiers'
      fullPath: '/dossiers'
      preLoaderRoute: typeof DossiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunites': {
      id: '/opportunites'
      path: '/opportunites'
      fullPath: '/opportunites'
      preLoaderRoute: typeof OpportunitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunites-detectees': {
      id: '/opportunites-detectees'
      path: '/opportunites-detectees'
      fullPath: '/opportunites-detectees'
      preLoaderRoute: typeof OpportunitesDetecteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseaux-sociaux': {
      id: '/reseaux-sociaux'
      path: '/reseaux-sociaux'
      fullPath: '/reseaux-sociaux'
      preLoaderRoute: typeof ReseauxSociauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appels-offres/$id': {
      id: '/appels-offres/$id'
      path: '/$id'
      fullPath: '/appels-offres/$id'
      preLoaderRoute: typeof AppelsOffresIdRouteImport
      parentRoute: typeof AppelsOffresRoute
    }
    '/opportunites/$id': {
      id: '/opportunites/$id'
      path: '/$id'
      fullPath: '/opportunites/$id'
      preLoaderRoute: typeof OpportunitesIdRouteImport
      parentRoute: typeof OpportunitesRoute
    }
  }
}

interface AppelsOffresRouteChildren {
  AppelsOffresIdRoute: typeof AppelsOffresIdRoute
}

const AppelsOffresRouteChildren: AppelsOffresRouteChildren = {
  AppelsOffresIdRoute: AppelsOffresIdRoute,
}

const AppelsOffresRouteWithChildren = AppelsOffresRoute._addFileChildren(
  AppelsOffresRouteChildren,
)

interface OpportunitesRouteChildren {
  OpportunitesIdRoute: typeof OpportunitesIdRoute
}

const OpportunitesRouteChildren: OpportunitesRouteChildren = {
  OpportunitesIdRoute: OpportunitesIdRoute,
}

const OpportunitesRouteWithChildren = OpportunitesRoute._addFileChildren(
  OpportunitesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffairesRoute: AffairesRoute,
  AppelsOffresRoute: AppelsOffresRouteWithChildren,
  CalendrierAoRoute: CalendrierAoRoute,
  CalendrierEditorialRoute: CalendrierEditorialRoute,
  ClientsRoute: ClientsRoute,
  CommandesRoute: CommandesRoute,
  CommandesInternesRoute: CommandesInternesRoute,
  ConsultationsRoute: ConsultationsRoute,
  DevisRoute: DevisRoute,
  DossiersRoute: DossiersRoute,
  OpportunitesRoute: OpportunitesRouteWithChildren,
  OpportunitesDetecteesRoute: OpportunitesDetecteesRoute,
  ReferencesRoute: ReferencesRoute,
  ReseauxSociauxRoute: ReseauxSociauxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
